# Generated by Django 6.0 on 2025-12-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band_membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_id', models.IntegerField(verbose_name='Band id')),
                ('musician_id', models.IntegerField(verbose_name='Musician id')),
                ('join_date', models.DateTimeField(verbose_name='Joined')),
            ],
        ),
        migrations.CreateModel(
            name='Bands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=100, verbose_name='Band name')),
                ('genre', models.CharField(max_length=50, verbose_name='Duration')),
                ('founded_date', models.DateTimeField(verbose_name='Founded')),
            ],
        ),
        migrations.CreateModel(
            name='Concerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert_title', models.CharField(max_length=200, verbose_name='Title')),
                ('venue_address', models.CharField(max_length=255, verbose_name='Address')),
                ('concert_date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Musicians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('telegram', models.CharField(max_length=100, verbose_name='Telegram')),
                ('instrument', models.CharField(max_length=100, verbose_name='Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Performances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_id', models.IntegerField(verbose_name='Band id')),
                ('concert_id', models.IntegerField(verbose_name='Concert id')),
                ('performance_order', models.IntegerField(verbose_name='Performance order')),
            ],
        ),
        migrations.CreateModel(
            name='Rehearsals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_id', models.IntegerField(verbose_name='band id')),
                ('rehearsal_date', models.DateTimeField(verbose_name='Date & time')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
            ],
        ),
    ]
